name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to main branch
      run: |
        rm -rf src/ public/ .gitignore package.json package-lock.json README.md .github/
        mv build/* . && rmdir build
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull --rebase
        git add -A
        git commit -m "Build & Deploy" || echo "No changes to commit"
        git push